PORTNAME=	libgdbstub
DISTVERSION=	g20200213
CATEGORIES=	emulators devel

MAINTAINER=	0mp@FreeBSD.org
COMMENT=	Simple freestanding GDB stub library for parsing the GDB serial remote protocol

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		cmake pkgconfig
USE_GITHUB=	yes
GH_ACCOUNT=	AlexanderEichner
GH_TAGNAME=	cef4b4fd4b2ab2e25bf336530a6093388b215471

.include <bsd.port.mk>
