# $FreeBSD$

PORTNAME=	libpspproxy
DISTVERSION=	g20200107
CATEGORIES=	emulators devel

MAINTAINER=	0mp@FreeBSD.org
COMMENT=	Userspace library to proxy PSP hardware accesses to a real PSP

LICENSE=	GPLv2 GPLv3 MIT
LICENSE_COMB=	multi
LICENSE_FILE_GPLv3=	${WRKSRC}/LICENSE
LICENSE_FILE_MIT=	${WRKSRC}/LICENSE_PTEditor

USES=		cmake pkgconfig
USE_GITHUB=	yes
GH_ACCOUNT=	PSPReverse
GH_TAGNAME=	7756d60

.include <bsd.port.mk>
